### ISSUE TITLE
Missing required files

### ISSUE THREAD

**Issue by sunnysai12345** [Aniruddha-Tapas/Style-Transfer-using-VGG-16-Model#1]
Include download.py in the folder.

**Comment by Aniruddha-Tapas** [comment]
Hi! Sorry, I accidentally left out the `download.py` from the repo. Have include it in this [update](https://github.com/Aniruddha-Tapas/Style-Transfer-using-VGG-16-Model/tree/4b9db7f133cb96f0395e6d2cf16c984f4785b295). Thanks for pointing it out. :)
